version: '2'
networks:
  extnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.1.0/24
        gateway: 10.1.1.1
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.2.0/24
        gateway: 10.1.2.1

services:
 xxe_01:
  image: php:7.0.8-apache
  privileged: true
  volumes:
    - ./class01:/var/www/html/
  restart: always
  networks:
    extnetwork:
      ipv4_address: 10.1.1.3
 
 xxe_02:
  image: php:7.0.8-apache
  privileged: true
  volumes:
    - ./class02:/var/www/html/
  restart: always
  networks:
    extnetwork:
      ipv4_address: 10.1.1.4

 CommandExec:
   image: php:7.0.8-apache
   privileged: true
   volumes:
     - ./CodeExec:/var/www/html
   restart: always
   networks:
     lan:
       ipv4_address: 10.1.2.3

 xxe_03:
   image: php:7.0.8-apache
   privileged: true
   volumes:
     - ./class03:/var/www/html/
   restart: always
   networks:
     extnetwork:
       ipv4_address: 10.1.1.5
     lan:
       ipv4_address: 10.1.2.5

 xxe_04:
   image: php:7.0.8-apache
   privileged: true
   volumes:
     - ./class04:/var/www/html/
     - ./phpini:/usr/local/etc/php/
   restart: always
   networks:
     extnetwork:
       ipv4_address: 10.1.1.6
     lan:
       ipv4_address: 10.1.2.6

 xxe_05:
   image: php:7.0.8-apache
   privileged: true
   volumes:
     - ./class05:/var/www/html/
   restart: always
   networks:
     extnetwork:
       ipv4_address: 10.1.1.7
   dns:
     - 114.114.114.114

 xxe_06:
   image: php:7.0.8-apache
   privileged: true
   volumes:
     - ./class06:/var/www/html/
   restart: always
   networks:
     extnetwork:
       ipv4_address: 10.1.1.8
   dns:
     - 114.114.114.114

 xxe_07:
   image: php:7.0.8-apache
   privileged: true
   volumes:
     - ./class07:/var/www/html/
   restart: always
   networks:
     extnetwork:
       ipv4_address: 10.1.1.9
   dns:
     - 114.114.114.114

 xxe_08:
  image: mcc0624/xxe08:3.0
  privileged: true
  restart: always
  networks:
    extnetwork:
      ipv4_address: 10.1.1.10

 apache:
   image: bitnami/apache:2.4.54
   restart: always
   networks:
     extnetwork:
       ipv4_address: 10.1.1.11
   ports:
     - "80:8080"
   volumes:
     - ./apache/index.html:/opt/bitnami/apache2/htdocs/index.html
     - ./apache/my_vhost.conf:/vhosts/my_vhost.conf